In [1]:
import pandas as pd

corpus = ["This is totally fine",
          "It is extremely awesome",
          "Very boring class"]

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

x = cv.fit(corpus)   # learn the vocabularies 
print(x)

CountVectorizer()


In [3]:
print(x.vocabulary_) # dictionary of words and their correspondin indices 

{'this': 7, 'is': 5, 'totally': 8, 'fine': 4, 'it': 6, 'extremely': 3, 'awesome': 0, 'very': 9, 'boring': 1, 'class': 2}


In [4]:
print(cv.get_feature_names())

['awesome', 'boring', 'class', 'extremely', 'fine', 'is', 'it', 'this', 'totally', 'very']


In [15]:
x = cv.transform(corpus)  # transforms the matrix into document_term_matrix
print(x)                 # Will print in which [i,j] there are non-zero values

  (0, 4)	1
  (0, 5)	1
  (0, 7)	1
  (0, 8)	1
  (1, 0)	1
  (1, 3)	1
  (1, 5)	1
  (1, 6)	1
  (2, 1)	1
  (2, 2)	1
  (2, 9)	1


In [14]:
print(x.shape)     # row --> 3(number of documents) and column --> 10(number of unique words)

(3, 10)


In [8]:
print(x.toarray())

[[0 0 0 0 1 1 0 1 1 0]
 [1 0 0 1 0 1 1 0 0 0]
 [0 1 1 0 0 0 0 0 0 1]]


In [3]:
## To represent the document-term matrix in a data-frame
df=pd.DataFrame(x.toarray(),columns = cv.get_feature_names())
print(df)

   awesome  boring  class  extremely  fine  is  it  this  totally  very
0        0       0      0          0     1   1   0     1        1     0
1        1       0      0          1     0   1   1     0        0     0
2        0       1      1          0     0   0   0     0        0     1


In [10]:
print(list1)
print(np.argsort(list1,axis=0))# Consider that the array is sorted,will return the indices of this sorted array

[90, 32, 89, 21]
[3 1 2 0]


In [23]:
print(list2)
print('Along the row : ')
print(*np.argsort(list2,axis=1))

print('Along the column : ')
print(*np.argsort(list2,axis=0))

[[1, 2, 3], [7, 8, 9], [4, 5, 6]]
Along the row : 
[0 1 2] [0 1 2] [0 1 2]
Along the column : 
[0 0 0] [2 2 2] [1 1 1]


In [22]:
list2=[
    [1,2,3],
    [7,8,9],
    [4,5,6] 
]

In [19]:
process_size = [10,40,20,30,50]
buffer_size  = [15,55,25,43,31]
diff = []

In [24]:
for i in range(len(process_size)):
    process = process_size[i]
    for j in range(len(buffer_size)):
            diff.append(abs(buffer_size[j]-process))
    minimum_element = min(diff)
    index   = diff.index(minimum_element)
    print("{} size Process{} goes into the block {}".format(process,i,index))    
    print(diff)
    diff = []

10 size Process0 goes into the block 0
[5, 45, 15, 33, 21]
40 size Process1 goes into the block 3
[25, 15, 15, 3, 9]
20 size Process2 goes into the block 0
[5, 35, 5, 23, 11]
30 size Process3 goes into the block 4
[15, 25, 5, 13, 1]
50 size Process4 goes into the block 1
[35, 5, 25, 7, 19]


In [44]:
for i in range(len(process_size)):
    process = process_size[i]
    for j in range(len(buffer_size)):
        if process<buffer_size[j]:
            diff.append(((abs(buffer_size[j]-process)),j))
    minimum_element = min(diff)
    
    print("Process{} of size {} is going into the block {}".format(i+1,process,minimum_element[1]+1))
    diff=[]

Process1 of size 10 is going into the block 1
Process2 of size 40 is going into the block 4
Process3 of size 20 is going into the block 3
Process4 of size 30 is going into the block 5
Process5 of size 50 is going into the block 2


In [37]:
process_size

[10, 40, 20, 30, 50]

In [38]:
buffer_size

[15, 55, 25, 43, 31]